services:
  - type: web
    name: manage-it
    env: php
    plan: free
    region: frankfurt
    buildCommand: |
      composer install --no-dev --prefer-dist --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
